---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)

dir <- "E:/project_folders/demography/wil/population_projections/"

test_1 <- readRDS(paste0(dir, "outputs/flexible_area_model/2021_based/bpo/newham_5 year constrained/population.rds")) %>% 
  mutate(variant = "constrained to short",
         type = "flex")

test_2 <- readRDS(paste0(dir, "outputs/flexible_area_model/2021_based/bpo/newham_10 year constrained/population.rds")) %>% 
  mutate(variant = "constrained to long",
         type = "flex")

test_3 <- readRDS(paste0(dir, "outputs/flexible_area_model/2021_based/bpo/newham_10 year unconstrained/population.rds")) %>% 
  mutate(variant = "unconstrained",
         type = "flex")

short <- readRDS(paste0(dir, "outputs/trend/2021/2021_TEST_SHORT_INT_MIG_FERT_22-12-12_1539/population.rds")) %>% 
  mutate(variant = "trend short",
         type = "trend")

long <- readRDS(paste0(dir, "outputs/trend/2021/2021_TEST_LONG_INT_MIG_FERT_22-12-12_1442/population.rds")) %>% 
  mutate(variant = "trend long",
         type = "trend")

cent_upper_2020 <- readRDS(paste0(dir, "outputs/trend/2020/2020_CC_central_upper_21-09-21_1259/population.rds")) %>%
  mutate(variant = "previous projection",
         type = "trend") %>% 
  select(names(long))

data <- bind_rows(test_1, test_2, test_3, short, long, cent_upper_2020)

```

```{r}
boroughs <- c(paste0("E0900000",1:9),paste0("E090000",10:33)) %>% 
  lapply(function(x){filter(data, gss_code == x) %>% 
      group_by(la_name, year, variant, type) %>% 
      summarise(popn = sum(popn)/1000, .groups = "drop_last") %>% 
      data.frame()
  })

charts <- boroughs %>% 
  lapply(function(x){
    filter(x, year > 2010) %>% 
      ggplot(aes(year, popn, colour = variant, linetype = type)) +
      geom_line(linewidth=1.1) +
      labs(y="population (k)") +
      ggtitle(unique(x$la_name))  +
      scale_color_manual(values=c("blue", "red", "black","blue", "red", "yellow"))
  })

```

```{r}
for(i in 1:33){
  print(charts[[i]])
}

```

```{r}


london <- data %>% 
  filter(substr(gss_code,1,3)=="E09") %>% 
  group_by(year, variant, type) %>% 
  summarise(popn = sum(popn)/1000000, .groups = "drop_last") %>% 
  data.frame() %>% 
  filter(year > 2019) %>% 
  ggplot(aes(year, popn, colour = variant, linetype = type)) +
  geom_line(linewidth=1.1) +
  labs(y="population (mil)") +
  ggtitle("London") +
  scale_color_manual(values=c("blue", "red", "black","blue", "red", "yellow"))

print(london)

```

```{r}

trend_2021 <- long
actual_2020_cc <- cent_upper_2020
cc_2021 <- readRDS("E:/project_folders/demography/wil/population_projections/outputs/trend/2021/2020_CC_central_upper_22-12-09_1437/population.rds") %>% 
  mutate(variant = "new 2020 projection",
         type = "trend") %>% 
  select(names(long))
cc_2021_covid <- readRDS("E:/project_folders/demography/wil/population_projections/outputs/trend/2021/2020_CC_central_upper_22-12-09_1439/population.rds") %>% 
  mutate(variant = "new 2020 with covid",
         type = "trend") %>% 
  select(names(long))

trend_projections <- bind_rows(trend_2021, actual_2020_cc, cc_2021, cc_2021_covid)

london_trend <- trend_projections %>% 
  filter(substr(gss_code,1,3)=="E09") %>% 
  group_by(year, variant, type) %>% 
  summarise(popn = sum(popn)/1000000, .groups = "drop_last") %>% 
  data.frame() %>% 
  filter(year > 2019) %>% 
  ggplot(aes(year, popn, colour = variant, linetype = type)) +
  geom_line(linewidth=1.1) +
  labs(y="population (mil)") +
  ggtitle("London") +
  scale_color_manual(values=c("green", "white", "black", "blue"))

print(london_trend)

```

```{r}
library(gglaplot)

mye <- filter(data, year %in% 2011:2021,
              variant %in% c("previous projection","trend long"),
              substr(gss_code,1,3)=="E09") %>% 
  mutate(variant = ifelse(substr(variant,1,1)=="p", "existing series", "revised series"))

mye <- mye %>% 
  filter(substr(variant,1,1)=="e" & year < 2021) %>% 
  bind_rows(filter(mye, substr(variant,1,1)=="r"))

mye_boroughs <- mye %>%
  group_by(gss_code, la_name, year, variant) %>% 
  summarise(population = sum(popn), .groups = 'drop_last') %>% 
  data.frame()

mye_ldn <- mye_boroughs %>% 
  group_by(year, variant) %>% 
  summarise(population = sum(population)/1000000, .groups = 'drop_last') %>% 
  data.frame()

```

```{r}

pal <- gla_pal(gla_theme = "default", palette_type = "highlight", n = c(1, 1))
theme_set(theme_gla(gla_theme = "default"))

plot1 <- mye_ldn %>% 
  ggplot(aes(year, population, colour = variant)) +
  ggla_line(size=1.1) +
  scale_colour_manual(values = pal) +
  ggla_highlight(filter_type = "end") +
  scale_x_continuous(expand = c(0.1, 0.1), limits = c(2011, 2021), breaks = seq(2011,2021,2))+
  labs(title = "Existing & Revised MYE Series, London",
       subtitle = "population (mil)",
       caption = "Source: ONS MYE & GLA experimental revised series \nNote: Revsied series is indicative only. Actual data yet to be produced.") 

plot1

image_root <- "Q:/Teams/D&PA/Admin/Liaison groups/Population Statistics User Group/2022/4. December/charts/"

ggsave(paste0(image_root, "london MYE.png"), plot = plot1, device = "png", width = 8, height = 4)


```

```{r}

plot_borough <- function(gss, nm){
  
  a <- mye_boroughs %>% 
    filter(gss_code == gss) %>% 
    ggplot(aes(year, population/1000, colour = variant)) +
    ggla_line(size=1.1) +
    scale_colour_manual(values = pal) +
    ggla_highlight(filter_type = "end") +
    scale_x_continuous(expand = c(0.1, 0.1), limits = c(2011, 2021), breaks = seq(2011,2021,2))+
    labs(title = paste0("Existing & Revised MYE Series, ", nm),
         subtitle = "population (thousands)",
         caption = "Source: ONS MYE & GLA experimental revised series \nNote: Revsied series is indicative only. Actual data yet to be produced.") 
  
  image_root <- "Q:/Teams/D&PA/Admin/Liaison groups/Population Statistics User Group/2022/4. December/charts/"
  
  ggsave(paste0(image_root, nm, " MYE.png"), plot = a, device = "png", width = 6, height = 6)
  
  a
}
```

```{r}

b <- test_1 %>% select(gss_code, la_name) %>% distinct()

for(i in 1:33){
  
  print(plot_borough(b[i,1], b[i,2]))
  
}

```

```{r}

plot_borough("E09000033", "Westminster")
plot_borough("E09000007", "Camden")

plot_borough("E09000005", "Ealing")
plot_borough("E09000015", "Harrow")

```
