---
title: "How to Use this Repository"
output:
  html_document:
    self_contained: no
    toc: true
    toc_float: true
---

The `2019_development` repository contains all the code for the new generation of GLA population models. The resulting product will be an ecosystem of different population cohort models, each built with a similar framework, combining reusable modules and input with model-specific code.

# Setting up

You will need your own local copy of this repository to do anything beyond running the models. If you're reading this on the GLA Q:/ drive, any changes you make to the code will be overwritten the next time someone pushes a new version.


### For running models only

If you're only running models, it's still recommended to follow the instructions here and run things locally. However if you don't use git, or need results quickly, you can set up and execute scripts in the `model_runs` folder without them being overwritten. See the relevant model documentation on how to do this.


### For development

If you want to run models locally or make any changes to the code, you'll need to clone the repository.

On the Q:/ drive everything is stored in a bare (uneditable) repository at `Q:\Teams\D&PA\Demography\Projections\2019_development.git` with a Git hook to recreate it at `Q:\Teams\D&PA\Demography\Projections\2019_development` after each push.

To make a local copy of the repository, open up Git Bash and run
```
git clone "Q:\Teams\D&PA\Demography\Projections\2019_development.git" "M:/Path/to/local/directory"
```
you can then navigate to the local directory and work with the code there. *Do not make changes to the master branch!* If you're doing any development work, start a new branch with
```
git checkout -b name-of-the-new-branch
```
This can then be merged later after it has been reviewed.

Please read the *Development Workflow and Best Practices* document in this folder before starting development, as this describes how we're going to implement good version control, code review and not-stepping-on-each-others'-toes.



# Repository Structure

The repository is split up in (what we hope is) a reasonably logical way. Code is separate from data which is separate from the scripts to set up and run models.

Many folders aren't part of the Git repository - these are mostly folders containing data that can be recreated using the scripts here.



### Folder structure

* `documentation`: source code and output for all high-level documentation.
* `input_data`: data for model input. Once things have got going everything in this folder will be generated by scripts within the `input_data_scripts` folder (so that everything is reproducible). Don't modify files here directly. Ignored by Git.
* `input_data_scripts`: scripts used to convert and process raw data to create whatever is needed for input to the models. Eventually these scripts will read only from the Demography database.
* `model_code`: the models themselves. The folder is split into 
    + `model_functions`: this is where all functions governing births, deaths, migration, ageing and various internal model checks are stored
    + `models`: each model that is built will have a folder here, containing functions to read in data, execute the model from start to finish and produce QA materials, a template configuration file, and a script to run the model
    + `output_automatic_QA`: a family of functions that will take the output of some models and run common checks and make reports with common plots
* `model_runs`: for each model, scripts and configuration files that can be edited and executed to run the model. Ignored by Git
* `notebooks_and_analysis`: a scrappy workspace for data exploration on your own machine. Ignored by Git
* `outputs`: location for model outputs. Ignored by Git. Don't modify files here directly.



### R project structure and Git

The whole of `2019_development` is a single R project and a single Git repository.

When pointing to files and folders in the project, always use the `here()` function, which is initialised in the project root directory.

Further down the line we may want to change this and split off separate parts of the project as individual packages, but for now, it will work as a single large ecosystem. That means, try not to duplicate function names, just in case.

**TODO**: set up `renv` to manage package versions






```{r session-info}
sessionInfo()
```
