---
params:
  set_title: !r paste0("Ward Profile - ",ward_name)
title: "ward profiles index"
output:
  html_document:
    number_sections: no
    includes:
      before_body: header.html
      after_body: footer.html
    css: "style.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```

```{r library, include=FALSE, echo = FALSE}
library(dplyr)
library(knitr)
library(DT)
library(data.table)
library(stringr)
```

```{r data, echo = FALSE}

stem <- "https://londondatastore-upload.s3.eu-west-1.amazonaws.com/Demography/ward_profiles/"
wards <- readRDS("input_data/lookup/2011_ward_to_district.rds") %>% 
  left_join(readRDS("input_data/lookup/gss_code_to_name.rds"),by = "gss_code") %>% 
  filter(substr(gss_code,1,3)=="E09") %>% 
  filter(gss_code != "E09000001") %>% 
  arrange(gss_code, ward_name) %>% 
  mutate(html_name = stringr::str_replace_all(gss_name," ", "_")) %>% 
  mutate(profile = paste0("<a target='_blank' href='", stem, html_name,"/",gss_code_ward,"_",ward_name,".html'>",ward_name," ward profile</a>")) %>% 
  select(gss_name, ward_name, profile) %>% 
  setnames(c("borough", "ward", "profile"))
```

```{r write_tables, echo = FALSE}
htmltools::tagList(
  lapply(split(wards, wards[, 1]), datatable, escape=FALSE, rownames=FALSE)
)
```