---
title: "How to Use this Repository"
output:
  html_document:
    keep_md: yes
    self_contained: yes
    toc: true
    toc_float: true
---

The `2019_development` repository (population_projections on GitHub) contains all the code for the new generation of GLA population models. The resulting product will be an ecosystem of different population cohort models, each built with a similar framework, combining reusable modules and input with model-specific code.

# Setting up

The most up-to-date version of the repository is on the GLA GitHub at https://github.com/Greater-London-Authority/population_projections/. There is also a copy on the GLA Q:/ drive, but this is frequently out of date.


### If you're running models only

If you're only running models and have access to the Q:/ drive and know it's up to date ... it's still recommended to follow the instructions below and run things locally.

However, if you don't use git, or need results quickly, you can set up and execute scripts in the `Q:\Teams\D&PA\Demography\Projections\2019_development\model_runs` folder without them being overwritten. See the relevant model documentation on how to do this. See the Workflow and Best Practices document for details on how to update the Q:/ drive repository.


### Setting up locally

If you want to run models locally or make any changes to the code, you'll need to clone the repository from GitHub.

Open up [Git Bash](https://gitforwindows.org/) (or any terminal that will run Git commands), navigate to the location you want to copy the repository to, and run
```
git clone https://github.com/Greater-London-Authority/population_projections/
```

Alternately you can do this in RStudio, via File > New Project > Version Control > Git, and filling in the URL above and a location for the repository.

### Installing the popmodules package

Most of the model functionality depends on a package within the repository called `popmodules`. Before you can run the model (either locally or on the Q:/ drive) you'll need to install it. The simplest way to do this is to open the `2019_development.Rproj` project file in RStudio (located in the repository root directory) and, from the console run
```
devtools::install("model_code/popmodules")
```
(If you haven't installed the `devtools` package, do that first.)

NOTE: the package will need reinstalling every time you download a new version of the repository - just re-run the above command, and select "None" when asked which dependent packages you want to update.



# Running a model

If all you want to do is run a model, its documentation should be in the `documentation/` folder, along with a template configuration script that can be edited and executed to run the model. Model output is written to the `output/` folder.



# Repository Structure

The repository is split up in (what we hope is) a reasonably logical way. Code is separate from data which is separate from the scripts to set up and run models.

Many folders aren't part of the Git repository - these are mostly folders containing data that can be recreated using the scripts here.



### Folder structure

* `documentation`: source code and output for all high-level documentation.
* `input_data`: data for model input. Once things have got going everything in this folder will be generated by scripts within the `input_data_scripts` folder (so that everything is reproducible). Don't modify files here directly. Ignored by Git.
* `input_data_scripts`: scripts used to convert and process raw data to create whatever is needed for input to the models. Eventually these scripts will read only from the Demography database.
* `model_code`: the models themselves. The folder is split into 
    + `model_scripts`: each model has a subfolder in this directory, containing the high-level model-specific functions that read in data, execute the model from start to finish and produce QA materials
    + `popmodules`: this is an R package containing functions for shared functionality across models, in particular births, deaths, migration, ageing and internal checks and validation. As it is an R package, function documentation and testing is also included here
    + `qa`: a family of R Markdown notebooks that will take the output of model runs, various custom parameters, and produce reports with common plots for the QA process
* `model_runs`: for each model, a plact to store configuration scripts for day-to-day work. These can be copied, editied and executed to run the model from templates in the `documentation/` folder. Ignored by Git
* `notebooks_and_analysis`: a scrappy workspace for data exploration on your own machine. Ignored by Git
* `outputs`: location for model outputs. Don't modify files here directly. Ignored by Git




### R project structure and Git

The whole of `2019_development` is a single R project and a single Git repository. The `model_code/popmodules/` folder is also an R project. If you're working on the functions within the package it makes sense to open this project, as it will enable RStudio's package load, package test and similar keyboard shortcuts.

When pointing to files and folders in the project, don't hard-code locations or assume the current working directory: instead use the `here()` function in ad-hoc scripts (which is initialised in the project root directory), and the `rprojroot` package for more robust formal stuff (such as model scripts or modules).

**TODO**: set up `renv` to manage package versions

