---
title: "How to Use this Repository"
output:
  html_document:
    keep_md: yes
    self_contained: yes
    toc: true
    toc_float: true
---

The `population_projections` repository on GitHub contains all the code for the new generation of GLA population models. The resulting product will be an ecosystem of different population cohort models, each built with a similar framework, combining reusable modules and input with model-specific code.

# Setting up

The most up-to-date version of the repository is on the GLA GitHub at https://github.com/Greater-London-Authority/population_projections/.

If you want to run models locally or make any changes to the code, you'll need to clone the repository from GitHub.

Open up [Git Bash](https://gitforwindows.org/) (or any terminal that will run Git commands), navigate to the location you want to copy the repository to, and run
```
git clone https://github.com/Greater-London-Authority/population_projections/
```

Alternately you can do this in RStudio, via File > New Project > Version Control > Git, and filling in the URL above and a location for the repository.

# Creating model input data

To create the necessary input data run the script `input_data_scripts/initialize.R`. Access to the Q: drive on the GLA network is necessary for this initialisation step however, once completed, models can be run locally without reference to the GLA network drives.

The initialize script will also install the `popmodules`, `trendmodel`, `housingledmodel` and `smallareamodel` packages and any other missing package dependencies.

# GLA models packages

If you want to update the model packages separately from the intialize process the simplest way to do this is to open the `population_projections.Rproj` project file in RStudio (located in the repository root directory) and, from the console run
```
devtools::install("model_code/popmodules")
```

This will install the current version of the `popmodules` package. You can then run the following `popmodules` function to update the other three packages:
```
popmodules::install_gla_models()
```
Alternatively, rather than installing a new versions of the packages you can load the development versions using the following `popmodules` function:
```
popmodules::load_gla_models()
```
This will run `devtools::load()` on all 4 GLA packages. Function parameters in both of the above functions allow you to specify which packages you want to install - see the package documentation for details.


# Running a model

To run a model you will need to use a config script. These text files list the parameters necessary to run the model and draw them together into a `config_list` which is passed to the `run_model` function of the particular model you are running. Examples of config files can be found in the `model_code/configs_scripts` folder.


# Repository Structure

The repository is split up in (what we hope is) a reasonably logical way. Code is separate from data which is separate from the scripts to set up and run models.

Many folders aren't part of the Git repository - these are mostly folders containing data that can be recreated using the scripts here.



### Folder structure

* `documentation`: high-level documentation on how to use the models
* `input_data`: model input data. Everything in this folder will be generated by scripts within the `input_data_scripts` folder (so that everything is reproducible). Don't modify files here directly. Ignored by Git.
* `input_data_scripts`: scripts used to convert and process raw data to create whatever is needed for input to the models.
* `model_code`: the models themselves, the configs, and associated scripts. The folder is split into 
    + `config_scripts` containing model configs for all models and for various setups. New configs should be saved here and will then be available to other users.
    + `model_scripts`: contains scripts that are not specific to individual models and which are not part of the `popmodules` package
    + `rmarkdown`: markdown files created for QA and BPO outputs.
    + `popmodules`: this is an R package containing functions for shared functionality across models. Includes functions for model processes, internal checks, tests, and validation. As it is an R package, function documentation and testing is also included here
    + `trendmodel`, `housingledmodel`, `smallareamodel`: The functions which manage the runing and output of the individual models
* `notebooks_and_analysis`: a scrappy workspace for data exploration on your own machine. Ignored by Git
* `outputs`: location for model outputs. Don't modify files here directly. Ignored by Git


### R project structure and Git

The whole of `population_projections` is a single R project and a single Git repository. The `model_code/popmodules/` folder is also an R project. If you're working on the functions within the package it makes sense to open this project, as it will enable RStudio's package load, package test and similar keyboard shortcuts.

When pointing to files and folders in the project, don't hard-code locations or assume the current working directory: instead use the `here()` function in ad-hoc scripts (which is initialised in the project root directory), and the `rprojroot` package for more robust formal stuff (such as model scripts or modules).

**TODO**: set up `renv` to manage package versions

